version: '3'

services:
  wp:
    image: wordpress:5.1.1-php7.3-apache
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    # - ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
    # - ./THEME-name:/var/www/html/wp-content/themes/THEME-name
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_DB=wordpress
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MAX_BACKUPS=2
      - INIT_RESTORE_LATEST=1
      - INIT_BACKUP= 0

      - CRON_TIME=0 */1 * * *
    restart: "no"

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080